<?php
/**
 * The clinical team, for team.php and — later — the individual location pages.
 *
 * Each person carries:
 *   slug         stable id; also the filename of their photo in assets/img/team/
 *   credentials  the letters after the name, kept apart so the card can style them
 *   group        psychiatry | therapy | leadership — the role filter on team.php
 *   states       the regions they work in, keys of 'locations' below
 *   clinics      the individual sites they see patients at, where we know them.
 *                Empty means we have the region but not the site yet; the card
 *                falls back to the region chip. Fill these in and the location
 *                pages can list their own team without touching team.php.
 *   video        a YouTube id for the short introduction, where one exists
 */

return [

    // The two regions, in the order the navigation lists them.
    'locations' => [
        'ca' => [
            'label'   => 'California',
            'short'   => 'CA',
            'region'  => 'Orange County & Greater Los Angeles',
            'blurb'   => 'Seven clinics from Newport Beach up through Long Beach and the South Bay, with telehealth across the state.',
            'clinics' => ['Newport Beach', 'Huntington Beach', 'Laguna Hills', 'Orange', 'Long Beach', 'Torrance', 'West Los Angeles'],
            'theme'   => 'bg-[#0e537c]',
        ],
        'tx' => [
            'label'   => 'Texas',
            'short'   => 'TX',
            'region'  => 'Austin, Dallas & Houston',
            'blurb'   => 'Eight clinics across three metros, offering TMS, psychiatry, therapy and Spravato® under one roof.',
            'clinics' => ['Central Austin', 'Cedar Park', 'Westlake', 'Central Dallas', 'Allen', 'Grapevine', 'Cypress', 'The Woodlands'],
            'theme'   => 'bg-[#203e35]',
        ],
    ],

    // The role filter. Order is the order the chips appear in.
    'roles' => [
        'psychiatry' => 'Psychiatry',
        'therapy'    => 'Therapy',
        'leadership' => 'Leadership',
    ],

    'people' => [
        [
            'slug'        => 'terry-v-eagan',
            'name'        => 'Terry V. Eagan',
            'credentials' => 'MD',
            'role'        => 'Chief Medical Officer',
            'group'       => 'leadership',
            'states'      => ['ca', 'tx'],
            'clinics'     => ['Laguna Hills, CA', 'Cedar Park, TX'],
            'photo'       => 'team/terry-v-eagan.jpg',
            'video'       => '',
            'bio'         => [
                'Dr. Terry Eagan brings to Anew Era TMS & Psychiatry an extensive body of professional experience in the field of psychiatry, encompassing both his clinical private practice and multiple Medical Director positions where he provides medical and psychiatric oversight of mental health treatment centers.  Dr. Eagan’s diverse background includes the founding of various institutes that focus on providing specialized and innovative treatment for a variety of psychiatric disorders.',
                'Dr. Eagan received his medical degree from the University of Tennessee College of Medicine, and completed an internship and residency at the Departments of Psychiatry and the Behavioral Sciences at USC.  Dr. Eagan provided clinical oversight over multiple clinical trials, served as a medical consultant to a variety of television shows, and is the author of multiple books in his field.',
                'Dr. Eagan’s diverse professional experience in treating depression, anxiety disorders, dual diagnoses, eating disorders, and more makes his contributions as Chief Medical Director of AnewEra TMS highly efficacious in improving client’s overall quality of life.',
            ],
        ],
        [
            'slug'        => 'allison-duggan',
            'name'        => 'Allison Duggan',
            'credentials' => '',
            'role'        => 'Regional Director',
            'group'       => 'leadership',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/allison-duggan.jpg',
            'video'       => '',
            'bio'         => [
                'Allison currently serves as Regional Director for Anew Era TMS & Psychiatry Texas. Her passion for mental wellness and excellence in patient care position her and her team to deliver world-class psychiatric care with the most advanced treatment technology available in the world.',
                'Allison is a natural-born entrepreneur, leader, and strategic business development specialist. She has decades of experience in leading large teams in the multifaceted environments of large-scale community management with a focus on achieving and sustaining profitability.    Additional expertise in determining process inefficiencies and launching successful replacement outlines,  interpersonal skills, and asset and investment management. Her excellence in this industry earned her multiple distinguished awards in leadership and profitability. Allison also achieved success in an online apparel boutique from a startup. She demonstrated mastery in online marketing, and social media engagement resulting in conversion and profitability.',
                'She is a Native Austinite whose extensive and valuable insight and love for the city will prove to be invaluable to the success of Anew Era TMS & Psychiatry Texas.',
            ],
        ],
        [
            'slug'        => 'evelyn-aki',
            'name'        => 'Evelyn Aki',
            'credentials' => '',
            'role'        => 'Psychiatric Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/evelyn-aki.jpg',
            'video'       => '',
            'bio'         => [
                'Evelyn is a board-certified psychiatric nurse practitioner who has over a decade of experience in providing mental health care. She is dedicated to providing compassionate care to individuals and their families struggling with mental health concerns, helping them navigate their mental health journey, and providing personalized care that addresses the unique needs of each client. Empowered with advanced knowledge and skills from a prestigious institution, Evelyn is committed to delivering evidence-based practices and offering solutions that are whole person centered. She believes in empowering individuals with knowledge and skills that promote lasting mental and physical wellness. Her practice emphasizes collaboration, health promotion education, psychoeducation, and empowerment, ensuring that clients are active participants in their treatment journey. Beyond clinical practice, Evelyn is passionate about shaping the future of healthcare through education. She has served in the preceptor role for other Nurse Practitioners which allows her to inspire and mentor the next generation of nursing professionals. She also enjoys learning about other cultures through travel and engagement to promote cultural competence.',
            ],
        ],
        [
            'slug'        => 'laura-ann-beaufford',
            'name'        => 'Laura Ann Beaufford',
            'credentials' => '',
            'role'        => 'Psychiatric Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/laura-ann-beaufford.jpg',
            'video'       => '',
            'bio'         => [
                'Laura was born in Waco, Texas and raised in Irving with three older half-brothers. After losing a brother to severe mental illness and police violence, she was inspired to pursue a career where she could make a real difference. She returned to college at age 41, earned her BSN from the University of Texas at Arlington in 2009, and worked in various nursing roles, including cardiac care, hospice, and case management.',
                'Laura later earned her MSN from Walden University and became a Psychiatric Mental Health Nurse Practitioner. She found her true calling in helping others heal through compassionate and informed mental health care.',
                'She currently provides care to adults 18 and older, offering inclusive, nonjudgmental support for all, including LGBTQ+ clients. Laura combines clinical expertise with empathy to create a safe space for healing and growth.',
            ],
        ],
        [
            'slug'        => 'priti-bhardwaj',
            'name'        => 'Priti Bhardwaj',
            'credentials' => 'MD',
            'role'        => 'Psychiatrist',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/priti-bhardwaj.jpg',
            'video'       => '',
            'bio'         => [
                'Dr. Priti Bhardwaj knows how difficult it can be to seek help, but by doing so you’re taking a step closer to where you want to be. Struggles with anxiety, depression, attention, and insecurity interfere with our emotional and physical well-being as well as our ability to connect with others. Her goal with patients and families is to provide a warm, safe, and accepting environment for them to communicate the difficulties and challenges they face and work on finding solutions that nourish them toward becoming the healthiest and best version of themselves. Dr. Priti is a double board-certified General Adult Psychiatrist who is also board certified in Integrative Medicine (ABIM). She will use her knowledge of psychopharmacology, psychotherapy, and holistic approaches to collaborate with you. Each person is seen as an individual and is encouraged to be an active participant in their own treatment.',
            ],
        ],
        [
            'slug'        => 'megha-chadha',
            'name'        => 'Megha Chadha',
            'credentials' => 'MD',
            'role'        => 'Psychiatrist',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/megha-chadha.jpg',
            'video'       => '',
            'bio'         => [
                'Dr. Megha Chadha is a board-certified psychiatrist dedicated to providing compassionate, evidence-based mental health care. She specializes in the treatment of mood disorders, including treatment-resistant depression, postpartum mental health conditions, ADHD, OCD, PTSD, and anxiety disorders.',
                'Dr. Chadha works collaboratively with patients to develop personalized treatment plans that support emotional well-being and long-term recovery. She also specializes in Transcranial Magnetic Stimulation (TMS), an FDA-cleared, non-invasive treatment for depression and other mental health conditions. Through a patient-centered approach, Dr. Chadha is committed to helping individuals achieve lasting improvements in their mental health and quality of life.',
            ],
        ],
        [
            'slug'        => 'doris-cudjoe',
            'name'        => 'Doris Cudjoe',
            'credentials' => '',
            'role'        => 'Psychiatric Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/doris-cudjoe.jpg',
            'video'       => '',
            'bio'         => [
                'Doris Cudjoe is a board-certified Psychiatric Mental Health Nurse Practitioner. She has over 12 years of critical care and psychiatric nursing experience and has worked for non-profit organizations as well as the federal government. She received a Bachelor of Arts in Philosophy from the University of Ghana, a Bachelor of Science in Nursing, and a Master of Science in Nursing from the University of Texas. Doris treats every patient as the unique individual they are. She is compassionate in her care and she pays attention to detail.',
                'Doris practices patient and family-centered care. She is married and has 3 beautiful daughters. She spends most of her free time homeschooling her kids, mentoring others who want to help people like she does, and working out.',
            ],
        ],
        [
            'slug'        => 'john-anthony-diya',
            'name'        => 'John Anthony Diya',
            'credentials' => 'MSN, FNP, PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/john-anthony-diya.jpg',
            'video'       => 'QC28vVZZe5Y',
            'bio'         => [
                'John Anthony Diya is a board-certified Psychiatric Mental Health NP, certified by the American Nurses Credentialing Center.',
                'He graduated from Charles R. Drew University. He has over 9 years of experience in providing psychiatric care to patients of all ages. He began his career in healthcare as a Registered Nurse working in both the inpatient and outpatient settings. His commitment to his patients and passion to deliver personalized and quality health care is what motivated him to advance his career as a Nurse Practitioner. In his downtime, John enjoys working out and playing golf. John is fluent in English and Tagalog.',
            ],
        ],
        [
            'slug'        => 'velma-hughes',
            'name'        => 'Velma Hughes',
            'credentials' => '',
            'role'        => 'Psychiatric Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/velma-hughes.jpg',
            'video'       => '',
            'bio'         => [
                'As a board-certified Family Psychiatric Mental Health Nurse Practitioner (PMHNP-BC), she provides compassionate, evidence-based care through a holistic, person-centered approach. She specializes in diagnosing and treating mental health conditions, developing individualized treatment plans, and prescribing medication when appropriate. She is passionate about helping patients achieve healing by addressing the mind, body, and soul in a supportive, judgment-free environment. She has a special interest in women’s mental health across the lifespan, including adolescence, pregnancy, postpartum, and menopause. Drawing from her personal experience with postpartum depression and anxiety, she offers genuine empathy, understanding, and hope to every patient she serves.',
            ],
        ],
        [
            'slug'        => 'dexter-jones',
            'name'        => 'Dexter Jones',
            'credentials' => 'MSN, PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/dexter-jones.jpg',
            'video'       => '',
            'bio'         => [
                'Dexter has more than 16 years of dedicated experience in the medical field, including three years as a Board-Certified Psychiatric Nurse Practitioner in California. Throughout his career, he has cultivated a strong foundation in primary psychiatric care, including acute, inpatient, and outpatient mental health. His many years of experience has equipped him with the knowledge and skills to deliver comprehensive mental healthcare to patients of diverse backgrounds and needs. Dexter uses a combination of medication management and supportive therapy to work towards the goals of decreasing suffering and improving quality of life.',
            ],
        ],
        [
            'slug'        => 'scarlett-kang',
            'name'        => 'Scarlett Kang',
            'credentials' => 'MSN, APRN, PMHNP-BC, FNP-C',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/scarlett-kang.jpg',
            'video'       => '',
            'bio'         => [
                'Ms. Scarlett S. Kang is a skilled adult psychiatric and mental health nurse practitioner. She practices at Anew Era TMS & Psychiatry in Torrance, CA. She offers both in-person and virtual care. Ms. Kang earned her master’s degree in nursing from Wilkes University. With her background in advanced mental health practice, she focuses on helping individuals navigate challenges that affect emotional and overall well-being. Ms. Kang provides thoughtful psychiatric care that integrates modern treatment approaches, supporting patients in finding stability and improved quality of life.',
            ],
        ],
        [
            'slug'        => 'swarna-kommireddy',
            'name'        => 'Swarna Kommireddy',
            'credentials' => 'MSN, RN, PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => ['Laguna Hills, CA'],
            'photo'       => 'team/swarna-kommireddy.jpg',
            'video'       => '',
            'bio'         => [
                'Swarna Kommireddy is a board certified Psychiatric Mental Health Nurse Practitioner dedicated to providing compassionate, evidence based, and individualized mental health care. She focuses on building trusting therapeutic relationships while respecting each patient’s unique needs, experiences, and treatment goals.',
                'She works with adolescents and adults experiencing depression, anxiety, bipolar disorder, ADHD, PTSD, and other psychiatric conditions. Her approach includes comprehensive assessment, medication management, patient education, and collaborative treatment planning.',
            ],
        ],
        [
            'slug'        => 'stephany-lavigne',
            'name'        => 'Stephany Lavigne',
            'credentials' => 'DNP, PMHNP-BC, APRN',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/stephany-lavigne.jpg',
            'video'       => 'vixYWNnNTtU',
            'bio'         => [
                'Stephany Lavigne, DNP is a board-certified Psychiatric Mental Health Nurse Practitioner. She received her Master of Science in Nursing from the University of South Alabama Cum Laude. She has over 7 years of experience working in mental health at the California State Hospital system, outpatient setting, and at the Veterans Affairs hospital. Her approach to treatment is one that is client-centered driven by the ethos of beneficence and her goal is to increase access to mental health care in underserved areas.',
                'In her spare time, she enjoys playing the saxophone & piano, singing, hiking, and traveling. Stephany is fluent in English and Bahasa Indonesia.',
            ],
        ],
        [
            'slug'        => 'rhoda-madamombe',
            'name'        => 'Rhoda Madamombe',
            'credentials' => '',
            'role'        => 'Psychiatric Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/rhoda-madamombe.jpg',
            'video'       => 'fgiRp3pP7pw',
            'bio'         => [
                'Rhoda Madamombe is a board-certified Psychiatric Mental Health Nurse Practitioner (MSN, PMHNP-BC) and a member of the American Psychiatric Association. She graduated from Wilkes University and has been in the field of psychiatry for the past 17 years.',
                'Rhoda has been with Medical City McKinney for 12 years holding various positions that include staff nurse, charge nurse, clinical supervisor, and currently nurse manager/PMHNP-BC. Rhoda is passionate about mental health nursing and is an advocate for high-quality patient care.',
                'In addition to her advocacy work against mental health stigma, Rhoda enjoys spending time with her family and their dog “Rocky.”',
            ],
        ],
        [
            'slug'        => 'randal-mcintyre',
            'name'        => 'Randal McIntyre',
            'credentials' => 'MD',
            'role'        => 'Child, adolescent and adult psychiatrist',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/randal-mcintyre.jpg',
            'video'       => '',
            'bio'         => [
                'Dr. Randal McIntyre has been practicing Child, Adolescent, and Adult Psychiatry in the Austin area for over thirty years. He was raised in Midland, Texas. He holds a BA in biology from The University of Texas – Austin, and an MD from The University of Texas Medical School – Houston. He did his internship in Family Practice at Southwestern Medical School in Dallas. Subsequently, he completed residences in General and Child Psychiatry at UTHCSC-Houston.',
                'He is in doubly Boarded Child and Adult Psychiatry by the American Board of Psychiatry and Neurology.',
                'Dr. McIntyre has also been a clinical professor through the University of Texas Medical Branch in Galveston and supervised students and residents for over twenty years, While his current practice is exclusively outpatient he has a long history of in and outpatient care.',
                'Due to his history in family practice, his clinical focus in holistic in nature, and recognizes the “mind-body connection”. Most of his diagnoses and treatments incorporate a bio-psycho-social model, psychopharmacology, and psychotherapy. He and his wife live in the Westlake area with their three (unruly) cats.',
            ],
        ],
        [
            'slug'        => 'tiffany-a-nix',
            'name'        => 'Tiffany A. Nix',
            'credentials' => 'MSN, PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/tiffany-a-nix.jpg',
            'video'       => '',
            'bio'         => [
                'Tiffany Nix is a Southern California-born native. A licensed and board-certified Psychiatric Mental Health Nurse practitioner across the lifespan. Graduating from Cal State University of Long Beach. Tiffany believes in creating a safe, honest, and therapeutic relationship with her clients. At Anew Era, Tiffany Nix specializes in adult treatment including but not limited to anxiety, depression, Bipolar, and dual diagnosis, and is certified in Transcranial Magnetic Stimulation treatment.',
                'Tiffany has been working in healthcare as an RN for the last 9 years, over the past 6 years she has been working primarily with dual-diagnosis patients in, inpatient, residential and outpatient settings. During graduate school, Tiffany focused her training on working with the underserved population.',
                'In her spare time, she enjoys painting, paddle boarding, and spending time with her family.',
            ],
        ],
        [
            'slug'        => 'abidemi-oladele',
            'name'        => 'Abidemi Oladele',
            'credentials' => 'MSN, PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => ['Cypress, TX', 'The Woodlands, TX'],
            'photo'       => 'team/abidemi-oladele.jpg',
            'video'       => '',
            'bio'         => [
                'Ms. Abidemi Oladele is a compassionate adult psychiatric and mental health nurse practitioner. Welcoming patients of all communities in Cypress, TX, she offers her services at Anew Era TMS & Psychiatry of Houston. She also takes virtual appointments. As part of her formal education and training, Ms. Oladele earned her master’s degree in nursing from Northern Kentucky University. Following a patient-centered approach during therapy, Ms. Oladele ensures each patient receives focused attention and feels comfortable sharing their struggles. She formulates realistic solutions, keeping their unique needs and preferences at the forefront.',
            ],
        ],
        [
            'slug'        => 'thao-palacio',
            'name'        => 'Thao Palacio',
            'credentials' => 'DNP, PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/thao-palacio.jpg',
            'video'       => '',
            'bio'         => [
                'Ms. Thao Palacio is a board-certified adult psychiatric and mental health nurse practitioner at Anew Era TMS & Psychiatry in Newport Beach, CA. She cares for adolescents and adults seeking support with a variety of mental health needs, with expertise in psychiatric evaluation, medication management, psychopharmacology, and supportive therapy.',
            ],
        ],
        [
            'slug'        => 'kammie-pierce',
            'name'        => 'Kammie Pierce',
            'credentials' => 'PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/kammie-pierce.jpg',
            'video'       => '',
            'bio'         => [
                'Kammie Pierce believes that true greatness begins with achieving equilibrium—when the mind and body are in balance, one can begin to reach their full potential. Her goal as a provider is to help patients to restore that balance, so that they can focus on what truly matters in life. Symptom remission is always a top priority, but her care goes beyond this; she aims to support lasting stability and growth from the inside out.',
                'Kammie brings experience across a range of clinical settings, including inpatient, outpatient, and residential care. Much of her background as a registered nurse was rooted in inpatient work, which gave her a strong foundation in acute psychiatric care. She has been practicing as a board-certified Psychiatric Mental Health Nurse Practitioner (PMHNP-BC) for approximately two years and remains committed to lifelong learning. Her updated knowledge is something she hopes to continue to share with her clients.',
                'She is a passionate advocate for underrepresented communities across all cultural, gender, and socioeconomic backgrounds, and strives to create a safe, inclusive environment for all. She earned both her bachelor’s and master’s degrees in nursing from West Coast University. Outside of work, she enjoys hiking, reading, and spending quality time with loved ones.',
            ],
        ],
        [
            'slug'        => 'frizette-pua',
            'name'        => 'Frizette Pua',
            'credentials' => 'MSN, PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/frizette-pua.jpg',
            'video'       => '',
            'bio'         => [
                'Frizette Dodson Pua is a Board Certified Psychiatric Mental Health Nurse Practitioner (PMHNP-BC). She earned her Master of Science in Nursing from Walden University. She has extensive experience of diverse healthcare settings, providing comprehensive support to individuals with wide range of mental health conditions. She is dedicated to delivering compassionate, evidence-based mental health care across the life span. With a strong clinical foundation and a collaborative, patient-centered approach, she works closely with interdisciplinary teams to ensure continuity of care and optimize treatment outcomes for individuals with complex mental health needs. Her practice emphasizes safety, respect, cultural humility, and empowering individuals to actively participate in their journey toward sustained wellness. Ms. Pua is deeply committed to reducing barriers to mental health services, enhancing patient education, and advancing initiatives that promote equity, resilience, and recovery within the communities she serves.',
            ],
        ],
        [
            'slug'        => 'ferdinand-andy-rimando',
            'name'        => 'Ferdinand Andy Rimando',
            'credentials' => 'PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/ferdinand-andy-rimando.jpg',
            'video'       => '',
            'bio'         => [
                'Ferdinand Andy Rimando, a Psychiatric Nurse Practitioner at Anew Era California since 2024, has an impressive 20-year journey in healthcare reflecting a diverse and accomplished career. His expertise spans various specialties, including sleep medicine, critical care, anesthesia, post-anesthesia care, psychiatry, and mental health.',
                'His commitment to excellence was evident during his nursing residency at Johns Hopkins Hospital in Baltimore, a prestigious institution known for its commitment to healthcare innovation and education. Andy’s dedication and skills have been recognized through his contributions to renowned medical centers, such as the University of Maryland Medical Center, Penn State Hershey Medical Center, Cedars Sinai Medical Center, Kaiser Permanente in Oakland, UCLA Health in Santa Monica, and his most recent position at Kure Medical Group, where he practiced interventional psychiatry modalities.',
                'Currently residing in Los Angeles, California, Andy continues to bring his wealth of experience, passion for healthcare, and a well-rounded perspective to his endeavors. His journey is a testament to his dedication to both professional excellence and personal growth',
            ],
        ],
        [
            'slug'        => 'diane-rodriguez',
            'name'        => 'Diane Rodriguez',
            'credentials' => 'MSN, PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['ca'],
            'clinics'     => ['Torrance, CA'],
            'photo'       => 'team/diane-rodriguez.jpg',
            'video'       => '',
            'bio'         => [
                'Diane Rodriguez, PMHNP-BC, is an ANCC board-certified Psychiatric Mental Health Nurse Practitioner who is passionate about helping individuals feel heard, understood, and supported throughout their mental health journey. She works with individuals experiencing concerns such as depression, anxiety, ADHD, trauma-related symptoms, bipolar disorder, and sleep difficulties. Diane believes that mental health care should be collaborative and individualized, with treatment guided by each person’s unique experiences, needs, and goals.',
            ],
        ],
        [
            'slug'        => 'sherri-sarumi',
            'name'        => 'Sherri Sarumi',
            'credentials' => 'DNP, APRN, PMHNP-BC',
            'role'        => 'Psychiatric Mental Health Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => ['The Woodlands, TX'],
            'photo'       => 'team/sherri-sarumi.jpg',
            'video'       => '',
            'bio'         => [
                'Sherri Sarumi, DNP, APRN, PMHNP-BC, is a board-certified Psychiatric Mental Health Nurse Practitioner with experience providing compassionate, evidence-based psychiatric care to adults across outpatient and substance use treatment settings. She is committed to delivering patient-centered care through comprehensive psychiatric evaluations, medication management, and individualized treatment planning  that promotes long-term mental wellness and recovery.',
            ],
        ],
        [
            'slug'        => 'yan-shi',
            'name'        => 'Yan Shi',
            'credentials' => '',
            'role'        => 'Psychiatric Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/yan-shi.jpg',
            'video'       => '',
            'bio'         => [
                'Yan Shi is a licensed Psychiatric-Mental Health Nurse Practitioner in Texas dedicated to providing compassionate, evidence-based mental health care. He earned his Master of Science in Nursing from the University of Texas at Arlington and began his medical education and clinical training in China before earning a PhD in Immunology from Peking Union Medical College.',
                'His research background includes 18 peer-reviewed publications in cancer research and immunology, providing him with a strong understanding of the connection between physical health, mental health, and overall well-being. With more than seven years of experience in hospital and mental health settings, he has worked with individuals from diverse backgrounds facing a wide range of emotional and psychiatric challenges.',
                'Committed to delivering high-quality, personalized care, Yan Shi stays current with the latest psychiatric research and evidence-based treatment approaches to support recovery, resilience, and long-term wellness. He believes in a collaborative approach to care and works closely with each client to develop a personalized treatment plan that aligns with each client’s goals, strengths, and values.',
            ],
        ],
        [
            'slug'        => 'bryan-walker',
            'name'        => 'Bryan Walker',
            'credentials' => '',
            'role'        => 'Psychiatric Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/bryan-walker.jpg',
            'video'       => '',
            'bio'         => [
                'Bryan Walker is an Advanced Practice Registered Nurse (APRN) and is board-certified in psychiatry and mental health (PMHNP-BC). As an advanced practice nurse, Bryan is committed to providing holistic, patient-centered, and evidenced-based care. He believes strongly in an integrated model of care and works in partnership with clients, other healthcare providers, and psychotherapists to achieve the best outcomes. Bryan keeps up with the latest research by attending conferences and improving psychotherapy skills with continued training. He completed his MSN at Eastern Kentucky University in Richmond, Kentucky. Bryan has also been a registered nurse since 1984 and has worked in a wide variety of health care settings (emergency, trauma, intensive care, home health, telephone triage, rehabilitation, hospice and palliative care, psychiatry). His diverse background augments his practice of psychiatry and mental health care.  Prior to entering private practice, Bryan worked full time at Cedar Crest Hospital and Residential Treatment Center. As a PMHNP, Bryan can assess, diagnose, and treat patients with psychiatric disorders including the prescription of medications and administration of psychotherapy. PMHNP’s provide a full range of psychiatric and mental health services.',
            ],
        ],
        [
            'slug'        => 'erick-willars',
            'name'        => 'Erick Willars',
            'credentials' => '',
            'role'        => 'Psychiatric Nurse Practitioner',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/erick-willars.jpg',
            'video'       => '',
            'bio'         => [
                'Erick is a psychiatric nurse practitioner who is here to support individuals on their mental health journey with compassion and care. Erick specializes in treating anxiety, depression, trauma and ADHD through personalized, evidence-based approaches. His goal is to create a space where patients feel truly heard and understood, working collaboratively to find the tools and treatments that work best for each person—one step at a time.',
                'Erick believes that every person’s mental health journey is unique. With that in mind, he works closely with patients to develop treatment plans tailored to each individual’s needs and goals. His approach blends evidence-based practices with medication management when appropriate, always emphasizing a holistic view of well-being. Erick’s therapeutic style is supportive and empathetic, encouraging patients to move at their own pace while working toward sustainable, positive change.',
            ],
        ],
        [
            'slug'        => 'xiaoyan-wu',
            'name'        => 'Xiaoyan Wu',
            'credentials' => 'MD',
            'role'        => 'Psychiatrist',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/xiaoyan-wu.jpg',
            'video'       => '',
            'bio'         => [
                'Dr. Wu initially graduated from a leading medical school in China and subsequently completed her psychiatric residency training program at Texas Tech University Medical School. During this time, Dr. Wu was elected as a chief psychiatric resident and received the honor of “Resident of the Year” twice.',
                'With 23 years of experience in general psychiatry, Dr. Wu has expertise in addressing a wide range of major psychiatric disorders and mental health issues. Dr. Wu’s practice encompasses familiarity with psychopharmacological interventions as well as common psychotherapeutic approaches to effectively manage everyday challenges.',
            ],
        ],
        [
            'slug'        => 'huiping-xu',
            'name'        => 'Huiping Xu',
            'credentials' => 'MD',
            'role'        => 'Psychiatrist',
            'group'       => 'psychiatry',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/huiping-xu.jpg',
            'video'       => '',
            'bio'         => [
                'Dr. Huiping Xu is a board-certified physician who specializes in holistic treatment philosophies. Dr. Xu received a master’s degree in neuroscience with a focus on learning and memory mechanisms, development and regeneration of the central nervous system. She then completed her psychiatry residency at McGovern Medical School at UT Health Science Center. Dr. Xu founded Wholehealth PLLC in 2015 to offer individualized and personalized care to patients. In 2018 Dr. Xu was awarded Top Psychiatrist in Houston, TX by the Patient Reviews for Top Doctors. She previously served as Assistant Professor of Baylor College of Medicine, prior to joining Anew Era TMS & Psychiatry in 2025.',
            ],
        ],
        [
            'slug'        => 'yolanda-acosta',
            'name'        => 'Yolanda Acosta',
            'credentials' => 'LCSW',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/yolanda-acosta.jpg',
            'video'       => '',
            'bio'         => [
                'Yolanda Acosta, LCSW, is a bilingual and culturally responsive clinical social worker with experience providing psychotherapy to adolescents, adults, and older adults from diverse backgrounds. Her clinical work is grounded in trauma-informed care and emphasizes creating a safe, collaborative, and compassionate therapeutic environment where clients can process difficult experiences while building insight, resilience, and meaningful change.',
                'Her clinical experience incorporates a range of evidence-based and evidence-informed practices, including EMDR, CBT, TF-CBT, ACT, MI, and SFBT. She integrates these approaches according to each client’s presenting concerns, developmental needs, cultural background, readiness for treatment, and individualized goals.',
                'She has particular experience integrating EMDR and trauma-focused interventions into her work with clients who have experienced complex and longstanding trauma. Her approach recognizes the impact that family systems, culture, and broader social environments can have on mental health and recovery (person-in-environment framework).',
                'As a clinician, Yolanda values the therapeutic relationship as an essential part of the healing process. Her approach balances warmth and empathy with clinical structure, assessment, and evidence-based interventions. She strives to help clients better understand their experiences, recognize their strengths, develop effective coping skills, and move forward with greater confidence and autonomy.',
            ],
        ],
        [
            'slug'        => 'christina-ferrari',
            'name'        => 'Christina Ferrari',
            'credentials' => 'MA, APCC',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/christina-ferrari.jpg',
            'video'       => '',
            'bio'         => [
                'Christina Ferrari is an Associate Professional Clinical Counselor and a graduate of Northwestern University with over 12 years of experience serving others in clinics, schools, and private settings. She collaborates with clients to explore goals, develop treatment plans, and build skills to help them integrate more fully into their lives. Christina’s approach is rooted in empirically based interventions, neuroscience, and psychoeducation.',
                'At her core, Christina believes in the power of connection and the transformative magic of feeling understood. She emphasizes the healing potential that emerges from sharing stories and building relationships focused on growth and recovery. By examining a client’s early life experiences, identifying patterns, and uncovering core beliefs, she helps create a mindful evaluation of these narratives, empowering clients to make intentional choices for their future.',
                'Christina embraces the philosophy that “pain is inevitable, but suffering is optional,” while also acknowledging the validity of individual suffering. Over the years, she has refined this perspective, inviting the idea that peace can be a conscious choice in the face of life’s challenges. For her, pain is inevitable, but peace remains an option.',
            ],
        ],
        [
            'slug'        => 'rickie-lanette-fleck',
            'name'        => 'Rickie Lanette Fleck',
            'credentials' => 'MSW, PhD, LCSW',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/rickie-lanette-fleck.jpg',
            'video'       => '',
            'bio'         => [
                'Rickie Lanette Fleck, PhD, is trained in EMDR and Motivational Interviewing and has experience utilizing CBT, ACT, and DBT in her clinical work.',
                'Her specialties include short-term, solution-focused therapy and working with caregiver wounds. She works with clients across the lifespan and has experience supporting individuals of various ages.',
                'A native Texan, Rickie earned both her undergraduate and graduate degrees from Texas State University and received her PhD from Our Lady of the Lake University in San Antonio. She is a member of the queer community and lives with her wife and family just outside of Austin.',
            ],
        ],
        [
            'slug'        => 'tameka-franklin',
            'name'        => 'Tameka Franklin',
            'credentials' => 'LPC-S',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['tx'],
            'clinics'     => ['The Woodlands, TX'],
            'photo'       => 'team/tameka-franklin.jpg',
            'video'       => '',
            'bio'         => [
                'Tameka`s approach is person-centered, collaborative, transparent, empathetic, and humorous. Tameka utilizes several modalities with some of them being Dialectical Behavioral Therapy (DBT), Cognitive Behavioral Therapy (CBT), Acceptance and Commitment Therapy (ACT), and Motivational Interviewing (MI). Tameka has experience in all levels of care within mental health. In addition to providing direct care for the past nine years, Tameka also has experience supervising counseling and social work interns along with LPC Associates. Tameka believes people possess an internal strength that is awaiting to be shown externally with the right support and guidance. Please contact us if you think Tameka may be a good fit for your needs.',
            ],
        ],
        [
            'slug'        => 'kenneth-gildar',
            'name'        => 'Kenneth Gildar',
            'credentials' => 'MA, AMFT',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/kenneth-gildar.jpg',
            'video'       => '',
            'bio'         => [
                'Ken Gildar is an Associate Marriage and Family Therapist based in Southern California. He has several years of experience working with adults and adolescents in the mental health field and has supported clients from diverse cultural and ethnic backgrounds. Ken specializes in helping individuals manage anxiety, depression, family conflict, work stress and addiction. Drawing from CBT and DBT, Ken helps clients build useful coping skills, emotional regulation, and resilience. Before becoming a therapist, he worked for several years as a drug counselor, an experience that continues to inform his down-to-earth approach. Ken is dedicated to helping people rediscover hope when life gets discouraging.',
            ],
        ],
        [
            'slug'        => 'john-andrew-hosier',
            'name'        => 'John Andrew Hosier',
            'credentials' => 'MS, LMFT',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/john-andrew-hosier.jpg',
            'video'       => '',
            'bio'         => [
                'John Andrew Hosier is a licensed Marriage and Family Therapist born and raised in Southern California. Andrew has work history in non-profit social service agencies, private psychiatric offices, inpatient addiction treatment centers and outpatient primary mental health facilities.',
                'He has extensive personal and professional experience working with addiction, anxiety, depression, relationship/family conflict and co-dependence. He operates from a psychodynamic perspective with influences of a humanistic person-centered approach, utilizing motivational interviewing and behavior-based approaches (CBT/ACT) to aid clients in achieving their own goals for therapy.',
                'John completed his bachelor’s degree in psychology and master’s degree in Clinical Psychology from Vanguard University of Southern California. When not doing therapy, Andrew is attempting to make his daughter and wife laugh while cuddling his corgi, reading books, watching sports and cycling.',
            ],
        ],
        [
            'slug'        => 'tria-ismay',
            'name'        => 'Tria Ismay',
            'credentials' => 'MA, AMFT, APCC',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/tria-ismay.jpg',
            'video'       => '',
            'bio'         => [
                'Tria is an Associate Marriage and Family Therapist (AMFT) and Associate Professional Clinical Counselor (APCC) who earned her master’s degree from Pepperdine University and completed her undergraduate studies at Sacramento State, where she was a student-athlete. She is passionate about creating a safe, collaborative, and supportive space for clients to explore healing and personal growth. She takes an integrative, client-centered approach and incorporates evidence-based practices such as EMDR, DBT, and Internal Family Systems (IFS) to meet each client’s unique needs and goals. Tria has experience working with a range of concerns, including trauma, anxiety, depression, and life transitions. She is committed to providing compassionate, culturally responsive care that supports clients in developing insight, emotional regulation, and resilience. Tria believes that each individual has the capacity for meaningful change and is especially passionate about helping clients connect with their core values. Her goal is to empower clients to live more intentional, authentic, and fulfilling lives.',
            ],
        ],
        [
            'slug'        => 'lauren-lopez',
            'name'        => 'Lauren Lopez',
            'credentials' => 'MA, AMFT',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/lauren-lopez.jpg',
            'video'       => '',
            'bio'         => [
                'Lauren Lopez is an Associate Marriage and Family therapist (AMFT) who graduated with a master’s degree in clinical psychology from Pepperdine University and who received a bachelor’s degree in psychology at the University of La Verne.',
                'She is passionate about creating a safe, collaborative, and supportive space for clients to explore their personal growth and healing. She works from a humanistic, person-centered approach and often incorporates evidence-based practices such as CBT, DBT, and ACT to meet clients’ unique needs and goals.',
                'Lauren’s professional experience spans across a variety of settings, including schools, residential treatment facilities, and behavioral health hospitals. These opportunities deepened her understanding of diverse populations and challenges, allowing her to offer compassionate, empathy, and culturally sensitive care.',
                'Lauren believes that everyone holds the potential for meaningful change, and her goal is to empower clients to navigate life’s complexities with resilience and clarity. Whether seeking support for anxiety, relationship challenges, or personal growth, Lauren will walk alongside you on your journey.',
            ],
        ],
        [
            'slug'        => 'kimberly-ann-morgan',
            'name'        => 'Kimberly Ann Morgan',
            'credentials' => 'MA, LMFT',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/kimberly-ann-morgan.jpg',
            'video'       => '',
            'bio'         => [
                'Kimberly Morgan, (she/her) MA, LMFT is a Licensed Marriage and Family Therapist specializing in working with anxiety, depression, couples, adolescents and parents, families, groups and athletes. She completed her MA in clinical psychology with a specialty in Applied Community Psychology at Antioch University, Los Angeles. Kimberly has worked in community mental health care and intensive outpatient settings with clients experiencing homeless, mental health issues and substance use disorders. She specializes in healing from loss and grief, and using strengths to process and heal from trauma.',
                'Therapeutic approaches include person centered therapy, motivational interviewing, family systems, CBT and DBT. Kimberly is an athlete who competes in swimming and triathlons and helps anxious athletes to cope with negative thinking and improve performance.',
            ],
        ],
        [
            'slug'        => 'terry-rauschuber',
            'name'        => 'Terry Rauschuber',
            'credentials' => 'LCSW',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/terry-rauschuber.jpg',
            'video'       => '',
            'bio'         => [
                'Terry Rauschuber is a Licensed Certified Social Worker with a master’s degree from The University of Texas at Austin. She is a mental health therapist with over 20 years of successful experience working with adults and seniors with depression and anxiety. She applies techniques to develop skills to learn how to manage negative thought processes and develop alternative thinking patterns. Terry’s experience in hospitals and psychiatric hospitals provides a wealth of knowledge of treatment modalities as well as maneuvering through the maze of healthcare. Terry has been active member in the social work community and has in the past served in various leadership capacities. She has presented at various workshops on “Suicide Assessment Risks for the Older Adult” as well as topics on depression and anxiety. When she is not working, she enjoys the outdoors, especially the beach and being with her grandchildren.',
            ],
        ],
        [
            'slug'        => 'clarissa-sourada',
            'name'        => 'Clarissa Sourada',
            'credentials' => 'MA, LPC, NCC',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/clarissa-sourada.jpg',
            'video'       => '',
            'bio'         => [
                'Clarissa believes therapy is a space for healing, self-discovery, and meaningful growth—a place where individuals can feel supported and empowered to become their most authentic selves. She approaches each person with respect, compassion, and sensitivity, creating a safe and collaborative environment where clients can explore their thoughts, emotions, relationships, and life experiences without judgment.',
                'Her goal is to help clients better understand themselves, gently challenge unhelpful thought patterns, and develop practical tools for navigating life’s challenges. Clarissa believes that meaningful change happens through connection, self-awareness, and building on the strengths each person already possesses.',
            ],
        ],
        [
            'slug'        => 'nicole-watson',
            'name'        => 'Nicole Watson',
            'credentials' => 'EdDCP, AMFT',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/nicole-watson.jpg',
            'video'       => '',
            'bio'         => [
                'Nicole Watson, Associate Marriage and Family Therapist, began working with Anew Era TMS and Psychiatry in August 2024. Currently, she is working as a Clinical Therapist supporting patients from the Long Beach, California office. In her role, Nicole provides one on one psychotherapy to new and existing patients. Nicole received her master’s degree in Marriage and Family Therapy and went on to earn her Doctor of Education in Counseling Psychology. She spent the past 7 years working for a non-profit dedicated to providing evidence-based practices to those experiencing newly onset symptoms of mental health concerns.',
            ],
        ],
        [
            'slug'        => 'krystal-michelle-wurm',
            'name'        => 'Krystal Michelle Wurm',
            'credentials' => '',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['tx'],
            'clinics'     => [],
            'photo'       => 'team/krystal-michelle-wurm.jpg',
            'video'       => '',
            'bio'         => [
                'Krystal Wurm approaches therapy as a collaborative partnership, empowering clients to be the ultimate decision-makers in their own lives while helping them identify opportunities and overcome obstacles. She provides a nonjudgmental, supportive space where clients can speak openly and feel heard.',
                'Having personally been diagnosed with ADHD, autism spectrum disorder (ASD), obsessive-compulsive disorder (OCD), anxiety, and depression, Krystal understands many of the challenges her clients experience. Her passion for becoming a Licensed Professional Counselor (LPC) was inspired by the support she received from a school therapist after the loss of her father at a young age.',
            ],
        ],
        [
            'slug'        => 'samantha-rodriguez-zuniga',
            'name'        => 'Samantha Rodriguez Zuniga',
            'credentials' => 'MS, AMFT',
            'role'        => 'Therapist',
            'group'       => 'therapy',
            'states'      => ['ca'],
            'clinics'     => [],
            'photo'       => 'team/samantha-rodriguez-zuniga.jpg',
            'video'       => '',
            'bio'         => [
                'Sam Rodriguez Zuniga is an Associate Marriage and Family Therapist (AMFT #150259) who earned a Master of Science degree in Counseling Psychology from Mount Saint Mary’s University. Her therapeutic style is humanistic and integrative which combines different therapeutic approaches to fit the needs of each unique individual. Her modalities include CBT/DBT/ACT/SFBT, Family Systems, and more. She has worked with adults dealing with depression, anxiety, grief, interpersonal conflict, family/relationship conflict, and life transitions. Her collaborative journey with clients honors and explores their past, personal experiences while also addressing current needs. Above all, she helps clients as they strive to become the best version of themselves.',
            ],
        ],
    ],
];
